old_sound_rabbit_mq:
    connections:
        default:
            host: '%env(RABBITMQ_HOST)%'
            port: '%env(int:RABBITMQ_PORT)%'
            user: '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASS)%'
            vhost: '/'
            lazy: true
            connection_timeout: 3
            read_write_timeout: 3

    producers:
        my_producer:
            connection:       default
            service_alias:    mq_producer
            exchange_options: { name: 'video_infos', type: direct }

    consumers:
        video_infos_consumer:
            connection:       default
            exchange_options: { name: 'video_infos', type: direct }
            queue_options:    { name: 'video_infos' }
            callback:         App\Message\VideoInfosConsumerService
